[package]
name = "rusty3bar"
version = "0.1.0"
authors = ["Gilad Naaman <gilad.naaman@gmail.com>"]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"

time = "0.1"
local-ip = "0.1"